document.addEventListener('DOMContentLoaded', () => {
        const companySelect = document.getElementById('companySelect');
            const newCompanyInput = document.getElementById('newCompanyName');
                const addCompanyBtn = document.getElementById('addCompanyBtn');

                    let companies = JSON.parse(localStorage.getItem('myCompanies')) || [
                            { id: 'comp_1', name: 'My First Company' }
                                ];

                                    function renderCompanies() {
                                            companySelect.innerHTML = '';
                                                    companies.forEach(comp => {
                                                                const option = document.createElement('option');
                                                                            option.value = comp.id;
                                                                                        option.textContent = comp.name;
                                                                                                    companySelect.appendChild(option);
                                                                                                            });

                                                                                                                    const savedCompany = localStorage.getItem('activeCompany');
                                                                                                                            if (savedCompany) {
                                                                                                                                        companySelect.value = savedCompany;
                                                                                                                                                }
                                                                                                                                                    }

                                                                                                                                                        addCompanyBtn.addEventListener('click', () => {
                                                                                                                                                                const name = newCompanyInput.value.trim();
                                                                                                                                                                        if (name) {
                                                                                                                                                                                    const newComp = { id: 'comp_' + Date.now(), name: name };
                                                                                                                                                                                                companies.push(newComp);
                                                                                                                                                                                                            localStorage.setItem('myCompanies', JSON.stringify(companies));
                                                                                                                                                                                                                        localStorage.setItem('activeCompany', newComp.id);
                                                                                                                                                                                                                                    newCompanyInput.value = '';
                                                                                                                                                                                                                                                renderCompanies();
                                                                                                                                                                                                                                                            loadCompanyData();
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                            companySelect.addEventListener('change', (e) => {
                                                                                                                                                                                                                                                                                    localStorage.setItem('activeCompany', e.target.value);
                                                                                                                                                                                                                                                                                            loadCompanyData();
                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                    // Form Submissions
                                                                                                                                                                                                                                                                                                        const financeForm = document.getElementById('financeForm');
                                                                                                                                                                                                                                                                                                            const orderForm = document.getElementById('orderForm');
                                                                                                                                                                                                                                                                                                                const employeeForm = document.getElementById('employeeForm');

                                                                                                                                                                                                                                                                                                                    financeForm.addEventListener('submit', (e) => {
                                                                                                                                                                                                                                                                                                                            e.preventDefault();
                                                                                                                                                                                                                                                                                                                                    const currentCompany = companySelect.value;
                                                                                                                                                                                                                                                                                                                                            const records = JSON.parse(localStorage.getItem('finances_' + currentCompany)) || [];
                                                                                                                                                                                                                                                                                                                                                    records.push({
                                                                                                                                                                                                                                                                                                                                                                amount: document.getElementById('financeAmount').value,
                                                                                                                                                                                                                                                                                                                                                                            type: document.getElementById('financeType').value,
                                                                                                                                                                                                                                                                                                                                                                                        date: new Date().toLocaleDateString()
                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                        localStorage.setItem('finances_' + currentCompany, JSON.stringify(records));
                                                                                                                                                                                                                                                                                                                                                                                                                financeForm.reset();
                                                                                                                                                                                                                                                                                                                                                                                                                        loadCompanyData();
                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                orderForm.addEventListener('submit', (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                        e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                                                                                const currentCompany = companySelect.value;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        const orders = JSON.parse(localStorage.getItem('orders_' + currentCompany)) || [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                orders.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            client: document.getElementById('clientName').value,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        total: document.getElementById('orderTotal').value,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    date: new Date().toLocaleDateString()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    localStorage.setItem('orders_' + currentCompany, JSON.stringify(orders));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            orderForm.reset();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    loadCompanyData();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            employeeForm.addEventListener('submit', (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const currentCompany = companySelect.value;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const employees = JSON.parse(localStorage.getItem('employees_' + currentCompany)) || [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            employees.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        name: document.getElementById('employeeName').value,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    role: document.getElementById('employeeRole').value
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    localStorage.setItem('employees_' + currentCompany, JSON.stringify(employees));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            employeeForm.reset();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    loadCompanyData();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Function to Load and Render Data based on selected company
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function loadCompanyData() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const currentCompany = companySelect.value;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 1. Render Financials
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const finances = JSON.parse(localStorage.getItem('finances_' + currentCompany)) || [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const financeList = document.getElementById('financeList');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        financeList.innerHTML = finances.length === 0 ? '<p style="color: #666;">No financial records found.</p>' :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '<ul>' + finances.map(f => `<li><strong>${f.type.toUpperCase()}:</strong> $${f.amount} (${f.date})</li>`).join('') + '</ul>';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 2. Render Orders
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const orders = JSON.parse(localStorage.getItem('orders_' + currentCompany)) || [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const orderList = document.getElementById('orderList');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    orderList.innerHTML = orders.length === 0 ? '<p style="color: #666;">No orders found.</p>' :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '<ul>' + orders.map(o => `<li><strong>Client:</strong> ${o.client} - $${o.total} (${o.date})</li>`).join('') + '</ul>';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // 3. Render Employees
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const employees = JSON.parse(localStorage.getItem('employees_' + currentCompany)) || [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const employeeList = document.getElementById('employeeList');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                employeeList.innerHTML = employees.length === 0 ? '<p style="color: #666;">No employees registered.</p>' :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '<ul>' + employees.map(e => `<li><strong>${e.name}</strong> - ${e.role}</li>`).join('') + '</ul>';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    renderCompanies();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        loadCompanyData();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
})
